---
title: "BeerProduction"
author: "PGC"
date: "4/16/2020"
output: html_document
editor_options: 
  chunk_output_type: console
owner: pgc
name: metrics_beer_production
metrics:
  nb_pounds:
    title: "# of Pounds Produced FOO"
    description: "Number of pounds used in beer prod in the US FOO"
dimensions:
  material_type:
    title: TypeFoo
    description: GrainFoo / non-grainFoo
  material:
    title: MaterialFoo
    description: WheatFoo, hops, corn, etc.
---

# Stopped at approx 52min [video](https://www.youtube.com/watch?v=1R4X09w7tQ8)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
theme_set(theme_light())

brewing_materials <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewing_materials.csv') %>% 
  mutate(date = ymd(paste(year, month , 1))) %>%
  filter(year < 2016)
beer_taxed <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_taxed.csv')
brewer_size <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewer_size.csv')
beer_states <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_states.csv')
```


```{r}
brewing_materials %>% count(material_type, type)

beer_taxed %>% count(tax_status)

brewer_size

beer_states
```


What ingredients are used in US beer prod.
```{r}
# Using forcats to reorder a factor variable based on numeric value in another column
brewing_materials %>%
  filter(date == max(date)) %>%
  filter(!str_detect(material_type, "Total")) %>%
  mutate(type = fct_reorder(type, month_current)) %>%
  ggplot(aes(type, month_current, fill=material_type)) +
  geom_col() + 
  coord_flip()

brewing_materials %>%
  filter(!str_detect(material_type, "Total")) %>%
  mutate(type = fct_reorder(type, month_current, sum )) %>%
  ggplot(aes(date, month_current, fill=type)) +
  geom_col() +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Time",
       y = "Pounds used in beer production",
       fill="type")


brewing_materials %>%
  filter(stringr::str_detect(material_type, "Total.*products")) %>%
  mutate(type = fct_reorder(type, month_current, sum )) %>%
  ggplot(aes(date, month_current, fill=type)) +
  geom_col() +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Time",
       y = "Pounds used in beer production",
       fill="TYPE")
```


```{r}
brewing_materials %>% count(type)
brewing_materials %>% count(material_type)
brewing_materials %>% count(data_type)
```


```{r}
brewing_materials %>%
  filter(material_type == "Total Used") %>%
  ggplot(aes(month, month_current, color=factor(year))) +
  geom_line() +
  expand_limits(y = 0)
```



Tidymetrics

```{r}
library(tidymetrics)
# approx time 17min
brewing_materials %>%
  rename(material = type) %>%
  filter(!stringr::str_detect(material_type, "Total")) %>%
  tidymetrics::cross_by_dimensions(material_type, material) %>%
  distinct (material_type, material)

brewing_summarized = brewing_materials %>%
  rename(material = type) %>%
  filter(!stringr::str_detect(material_type, "Total")) %>%
  tidymetrics::cross_by_dimensions(material_type, material) %>%
  tidymetrics::cross_by_periods(c("month", "quarter", "year")) %>%
  summarize(nb_pounds = sum(month_current)) %>% 
  ungroup()

# approx time ~20min
brewing_summarized %>%
  filter(material_type == "All", material=="All", period=="quarter") %>%
  ggplot(aes(date, nb_pounds)) +
  geom_col()


# visualize by Material Type
brewing_summarized %>%
  filter(material_type != "All", material=="All", period=="quarter") %>%
  ggplot(aes(date, nb_pounds, fill= material_type)) +
  geom_col()

# visualize by Material by Year (~21 min)
brewing_summarized %>%
  filter(material_type == "All", material!="All", period=="year") %>%
  ggplot(aes(date, nb_pounds, fill= material)) +
  geom_col()
```

ShinyMetrics
```{r}
use_metrics_scaffold(brewing_summarized)
brewing_metrics = create_metrics(brewing_summarized)
library(shinymetrics)
preview_metric(brewing_metrics$beer_production_nb_pounds)
```


## Brewer Size
- He said this highlights how to order factor in ggplot legend and to lump low factors into one group 
```{r}
brewer_size %>%
  filter(brewer_size != "Total", !is.na(total_barrels)) %>%
  mutate(parse_number = parse_number(brewer_size)) %>%
  mutate(brewer_size = fct_lump(brewer_size, 5, w = total_barrels),
         barrel_number = coalesce(parse_number(as.character(brewer_size)), 1),
         brewer_size = fct_reorder(brewer_size, barrel_number)) %>%
  ggplot(aes(year, total_barrels, fill=brewer_size)) + 
  geom_col()

# Seems like some missing data in the plot. Notice that there is no Blue in 2009 and 2010
# Determine which Brewwer_sizes have missing data for 1 or more Years
brewer_size %>% group_by(brewer_size) %>% summarize_each(list(MinYear = min, MaxYear = max, NumYears = n_distinct), year) %>% mutate(MaxNumYear = max(NumYears), NumMissingYears = MaxNumYear - NumYears) %>% filter(NumYears < MaxNumYear)
```


## Beer States - where is beer produced?
```{r}
beer_states %>% count(type, sort =T, wt = barrels)

beer_states %>%
  group_by(year) %>%
  summarize(barrels = sum(barrels, na.rm=T))

# who consumes beer on premises
beer_states %>%
  filter(type=="On Premises", year == max(year), state != "total") %>% arrange(-barrels)

# what State has highest On Prem in terms of percentage across the 3 types 
state_percents_2019 = beer_states %>%
  filter(year == max(year), state != "total") %>%
  group_by(state) %>%
  mutate(percent = barrels/sum(barrels)) %>%
  ungroup()

state_percents_2019 %>% 
  filter(type == "On Premises") %>% arrange(-percent)
```



```{r}
library(maps)
library(sf)
states = st_as_sf(map("state", plot=F, fill=T))

state.name
state.abb

statejoined=state_percents_2019 %>%
  mutate(ID = stringr::str_to_lower(state.name[match(state, state.abb)])) %>%
  inner_join(states, by="ID")

statejoined %>%
  ggplot(aes(geometry = geom, fill=percent)) +
  geom_sf() + 
  scale_fill_gradient2(low="blue", high="red", midpoint=.5,
                       labels = scales::percent)+
  facet_wrap(~type, nrow=2)+
  ggthemes::theme_map() +
  theme(legend.position = "right") +
  labs(title="How is beer consumed in the US?",
       fill="% consumed on prem.")
```


What about how things change over time?
```{r}
library(gganimate)
allyearsjoined = beer_states %>%
  filter(state != "total") %>%
  group_by(state, year) %>%
  mutate(percent = barrels/sum(barrels)) %>%
  ungroup() %>%
  mutate(ID = stringr::str_to_lower(state.name[match(state, state.abb)])) %>%
  inner_join(states, by="ID")


p = allyearsjoined %>%
  ggplot(aes(geometry = geom, fill=percent)) +
  geom_sf() + 
  facet_wrap(~type, nrow=2) +
  scale_fill_gradient2(low="blue", high="red", midpoint=.5,
                       labels = scales::percent)+
  ggthemes::theme_map() +
  theme(legend.position = "right") +
  labs(title="How is beer consumed in the US? ({ as.integer(frame_time) })",
       fill="% consumed on prem.")

p2 = p + transition_time(year)

animate(p2, renderer = gifski_renderer())
```

